{{- if .Values.zabbixweb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-web
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-web
    app.kubernetes.io/name: zabbix-web
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-web
spec:
  replicas: {{ .Values.zabbixweb.replicaCount }}
  selector:
    matchLabels:
      app:  {{ template "zabbix.fullname" . }}-zabbix-web
  template:
    metadata:
      labels:
        app: {{ template "zabbix.fullname" . }}-zabbix-web
        app.kubernetes.io/name: zabbix-web
        helm.sh/chart: {{ include "zabbix.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-web
        app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-web
    spec:
      {{- with .Values.zabbixweb.extraPodSpecs }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.zabbixweb.extraInitContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.affinity) 0 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.zabbixweb.pod_anti_affinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-web
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: zabbix-web
        resources:
          {{- toYaml .Values.zabbixweb.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.zabbixweb.image.tag }}
        image: "{{ .Values.zabbixweb.image.repository }}:{{ .Values.zabbixweb.image.tag }}"
        {{- else }}
        image: "{{ .Values.zabbixweb.image.repository }}:{{ .Values.zabbix_image_tag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.zabbixweb.image.pullPolicy }}
        env:
          {{- include "zabbix.db_access.env_vars" (list $ . "zabbix") | nindent 10 }}
          {{- range $item := .Values.zabbixweb.extraEnv }}
          - name: {{ $item.name }}
            value: {{ $item.value | quote  }}
          {{- end }}
        ports:
          - name: zabbix-web
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        {{- if .Values.zabbixweb.saml_certs_secret_name }}
          - name: zabbix-web-samlcerts
            mountPath: /etc/zabbix/web/certs
        {{- end }}
        {{- with .Values.zabbixweb.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: {{ .Values.zabbixweb.livenessProbe.path }}
            port: zabbix-web
          initialDelaySeconds: {{ .Values.zabbixweb.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.zabbixweb.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.zabbixweb.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.zabbixweb.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.zabbixweb.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.zabbixweb.readinessProbe.path }}
            port: zabbix-web
          initialDelaySeconds: {{ .Values.zabbixweb.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.zabbixweb.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.zabbixweb.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.zabbixweb.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.zabbixweb.readinessProbe.failureThreshold }}
      {{- with .Values.zabbixweb.extraContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      imagePullSecrets:
      {{- range .Values.zabbixweb.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      volumes:
      {{- if .Values.zabbixweb.saml_certs_secret_name }}
        - name: zabbix-web-samlcerts
          secret:
            secretName: {{ .Values.zabbixweb.saml_certs_secret_name }}
      {{- end }}
      {{- with .Values.zabbixweb.extraVolumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
